server:
  port: 9001
spring:
  application:
    name: licong‐base #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url:
    username: root
    password:
    jpa:
      database: MySQL
      show‐sql: true
      generate‐ddl: true