server:
  port: 9001
spring:
  application:
    name: licong-label
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url:
    username:
    password:
    jpa:
      database: MySQL
      show‐sql: true
      generate‐ddl: true
eureka:
  client:
    service‐url:
        defaultZone: http://localhost:6868/eureka
  instance:
    prefer‐ip‐address: true
jwt:
  config:
    key:
    ttl: 360000