server:
  port: 9002
spring:
  application:
    name: licong-note #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url:
    username:
    password:
    jpa:
      database: MySQL
      show‐sql: true
      generate‐ddl: true
  redis:
    host:
    port:
eureka:
  client:
    service‐url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer‐ip‐address: true
jwt:
  config:
    key: licong
    ttl: 2592000000
feign:
  client:
    config:
      default:
        connectTimeout: 500000
        # 请求 超时时间
        readTimeout: 500000
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 500000